framework:
    cache:
        prefix_seed: busway_cache
        app: cache.adapter.filesystem
        pools:
            cache.flight_data:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
            cache.api_response:
                adapter: cache.adapter.filesystem
                default_lifetime: 600
